const allIITsAndNITs = [
  { value: "Indian Institute of Technology Madras", label: "Indian Institute of Technology Madras" },
  { value: "Indian Institute of Technology Delhi", label: "Indian Institute of Technology Delhi" },
  { value: "Indian Institute of Technology Bombay", label: "Indian Institute of Technology Bombay" },
  { value: "Indian Institute of Technology Kanpur", label: "Indian Institute of Technology Kanpur" },
  { value: "Indian Institute of Technology Kharagpur", label: "Indian Institute of Technology Kharagpur" },
  { value: "Indian Institute of Technology Roorkee", label: "Indian Institute of Technology Roorkee" },
  { value: "Indian Institute of Technology Guwahati", label: "Indian Institute of Technology Guwahati" },
  { value: "Indian Institute of Technology Hyderabad", label: "Indian Institute of Technology Hyderabad" },
  { value: "Indian Institute of Technology Indore", label: "Indian Institute of Technology Indore" },
  { value: "Indian Institute of Technology (ISM) Dhanbad", label: "Indian Institute of Technology (ISM) Dhanbad" },
  { value: "Indian Institute of Technology Bhubaneswar", label: "Indian Institute of Technology Bhubaneswar" },
  { value: "Indian Institute of Technology Gandhinagar", label: "Indian Institute of Technology Gandhinagar" },
  { value: "Indian Institute of Technology Ropar", label: "Indian Institute of Technology Ropar" },
  { value: "Indian Institute of Technology Jodhpur", label: "Indian Institute of Technology Jodhpur" },
  { value: "Indian Institute of Technology Patna", label: "Indian Institute of Technology Patna" },
  { value: "Indian Institute of Technology Mandi", label: "Indian Institute of Technology Mandi" },
  { value: "Indian Institute of Technology Palakkad", label: "Indian Institute of Technology Palakkad" },
  { value: "Indian Institute of Technology Tirupati", label: "Indian Institute of Technology Tirupati" },
  { value: "Indian Institute of Technology Bhilai", label: "Indian Institute of Technology Bhilai" },
  { value: "Indian Institute of Technology Goa", label: "Indian Institute of Technology Goa" },
  { value: "Indian Institute of Technology Jammu", label: "Indian Institute of Technology Jammu" },
  { value: "Indian Institute of Technology Dharwad", label: "Indian Institute of Technology Dharwad" },

  // NITs
  { value: "National Institute of Technology Tiruchirappalli", label: "National Institute of Technology Tiruchirappalli" },
  { value: "National Institute of Technology Karnataka, Surathkal", label: "National Institute of Technology Karnataka, Surathkal" },
  { value: "National Institute of Technology Rourkela", label: "National Institute of Technology Rourkela" },
  { value: "National Institute of Technology Warangal", label: "National Institute of Technology Warangal" },
  { value: "National Institute of Technology Calicut", label: "National Institute of Technology Calicut" },
  { value: "Visvesvaraya National Institute of Technology, Nagpur", label: "Visvesvaraya National Institute of Technology, Nagpur" },
  { value: "Motilal Nehru National Institute of Technology Allahabad", label: "Motilal Nehru National Institute of Technology Allahabad" },
  { value: "Malaviya National Institute of Technology Jaipur", label: "Malaviya National Institute of Technology Jaipur" },
  { value: "Sardar Vallabhbhai National Institute of Technology Surat", label: "Sardar Vallabhbhai National Institute of Technology Surat" },
  { value: "National Institute of Technology Kurukshetra", label: "National Institute of Technology Kurukshetra" },
  { value: "Dr. B. R. Ambedkar National Institute of Technology Jalandhar", label: "Dr. B. R. Ambedkar National Institute of Technology Jalandhar" },
  { value: "Maulana Azad National Institute of Technology Bhopal", label: "Maulana Azad National Institute of Technology Bhopal" },
  { value: "National Institute of Technology Durgapur", label: "National Institute of Technology Durgapur" },
  { value: "National Institute of Technology Jamshedpur", label: "National Institute of Technology Jamshedpur" },
  { value: "National Institute of Technology Silchar", label: "National Institute of Technology Silchar" },
  { value: "National Institute of Technology Hamirpur", label: "National Institute of Technology Hamirpur" },
  { value: "National Institute of Technology Patna", label: "National Institute of Technology Patna" },
  { value: "National Institute of Technology Raipur", label: "National Institute of Technology Raipur" },
  { value: "National Institute of Technology Meghalaya", label: "National Institute of Technology Meghalaya" },
  { value: "National Institute of Technology Agartala", label: "National Institute of Technology Agartala" },
  { value: "National Institute of Technology Arunachal Pradesh", label: "National Institute of Technology Arunachal Pradesh" },
  { value: "National Institute of Technology Delhi", label: "National Institute of Technology Delhi" },
  { value: "National Institute of Technology Goa", label: "National Institute of Technology Goa" },
  { value: "National Institute of Technology Manipur", label: "National Institute of Technology Manipur" },
  { value: "National Institute of Technology Mizoram", label: "National Institute of Technology Mizoram" },
  { value: "National Institute of Technology Nagaland", label: "National Institute of Technology Nagaland" },
  { value: "National Institute of Technology Puducherry", label: "National Institute of Technology Puducherry" },
  { value: "National Institute of Technology Sikkim", label: "National Institute of Technology Sikkim" },
  { value: "National Institute of Technology Srinagar", label: "National Institute of Technology Srinagar" },
  { value: "National Institute of Technology Uttarakhand", label: "National Institute of Technology Uttarakhand" },
  { value: "National Institute of Technology Andhra Pradesh", label: "National Institute of Technology Andhra Pradesh" },

  // IIITs
  { value: "Indian Institute of Information Technology Hyderabad", label: "Indian Institute of Information Technology Hyderabad" },
  { value: "Indian Institute of Information Technology Allahabad", label: "Indian Institute of Information Technology Allahabad" },
  { value: "Indian Institute of Information Technology Gwalior", label: "Indian Institute of Information Technology Gwalior" },
  { value: "Indian Institute of Information Technology Jabalpur", label: "Indian Institute of Information Technology Jabalpur" },
  { value: "Indian Institute of Information Technology Guwahati", label: "Indian Institute of Information Technology Guwahati" },
  { value: "Indian Institute of Information Technology Kancheepuram", label: "Indian Institute of Information Technology Kancheepuram" },

  // State / Private
  { value: "Jadavpur University, Kolkata", label: "Jadavpur University, Kolkata" },
  { value: "Anna University, Chennai", label: "Anna University, Chennai" },
  { value: "Institute of Chemical Technology, Mumbai", label: "Institute of Chemical Technology, Mumbai" },
  { value: "College of Engineering, Pune (COEP)", label: "College of Engineering, Pune (COEP)" },
  { value: "Delhi Technological University (DTU)", label: "Delhi Technological University (DTU)" },
  { value: "Netaji Subhas University of Technology (NSUT), Delhi", label: "Netaji Subhas University of Technology (NSUT), Delhi" },
  { value: "Punjab Engineering College (PEC), Chandigarh", label: "Punjab Engineering College (PEC), Chandigarh" },
  { value: "Veermata Jijabai Technological Institute (VJTI), Mumbai", label: "Veermata Jijabai Technological Institute (VJTI), Mumbai" },
  { value: "Bengal Engineering and Science University (IIEST), Shibpur", label: "Bengal Engineering and Science University (IIEST), Shibpur" },
  { value: "Government College of Engineering, Amravati", label: "Government College of Engineering, Amravati" },
  { value: "University Institute of Engineering and Technology (UIET), Chandigarh", label: "University Institute of Engineering and Technology (UIET), Chandigarh" },
  { value: "Vellore Institute of Technology (VIT), Vellore", label: "Vellore Institute of Technology (VIT), Vellore" },
  { value: "Birla Institute of Technology and Science (BITS), Pilani", label: "Birla Institute of Technology and Science (BITS), Pilani" },
  { value: "Amrita Vishwa Vidyapeetham, Coimbatore", label: "Amrita Vishwa Vidyapeetham, Coimbatore" },
  { value: "Manipal Institute of Technology (MIT), Manipal", label: "Manipal Institute of Technology (MIT), Manipal" },
  { value: "SRM Institute of Science and Technology, Chennai", label: "SRM Institute of Science and Technology, Chennai" },
  { value: "Shiv Nadar University, Uttar Pradesh", label: "Shiv Nadar University, Uttar Pradesh" },
  { value: "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar", label: "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar" },
  { value: "PSG College of Technology, Coimbatore", label: "PSG College of Technology, Coimbatore" },
  { value: "SASTRA Deemed University, Thanjavur", label: "SASTRA Deemed University, Thanjavur" },
  { value: "Sharda University, Greater Noida", label: "Sharda University, Greater Noida" },
  { value: "DAIICT, Gandhinagar (Dhirubhai Ambani Institute of ICT)", label: "DAIICT, Gandhinagar (Dhirubhai Ambani Institute of ICT)" },
  { value: "Jaypee Institute of Information Technology, Noida", label: "Jaypee Institute of Information Technology, Noida" },
  { value: "BMS College of Engineering, Bengaluru", label: "BMS College of Engineering, Bengaluru" },
  { value: "R.V. College of Engineering, Bengaluru", label: "R.V. College of Engineering, Bengaluru" },
  { value: "Chandigarh University, Mohali", label: "Chandigarh University, Mohali" },
  { value: "LNMIIT, Jaipur (Laxmi Niwas Mittal Institute of IT)", label: "LNMIIT, Jaipur (Laxmi Niwas Mittal Institute of IT)" },
  { value: "Lovely Professional University (LPU), Punjab", label: "Lovely Professional University (LPU), Punjab" },
  { value: "NMIMS Mukesh Patel School of Technology, Mumbai", label: "NMIMS Mukesh Patel School of Technology, Mumbai" },
  { value: "Graphic Era University, Dehradun", label: "Graphic Era University, Dehradun" },
];

export default allIITsAndNITs;
